const KEY='ntV6';
const defaults={balance:1000,name:'Demo Trader',trades:[],transactions:[],chat:[]};
const state=Object.assign(defaults,JSON.parse(localStorage.getItem(KEY)||'null')||{});
const $=s=>document.querySelector(s); const money=n=>'$'+Number(n).toFixed(2); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function toast(msg){const e=$('#toast');if(!e)return;e.textContent=msg;e.style.display='block';clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.style.display='none',2600)}
function shell(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const name=$('#accountName');if(name)name.textContent=state.name;const bal=$('#balance');if(bal)bal.textContent=money(state.balance)}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>location.href=b.dataset.page==='trade'?'index.html':b.dataset.page+'.html')}
function common(){nav();shell(document.body.dataset.page||'trade')}
function addTransaction(type,amount,status='COMPLETED'){state.transactions.push({id:Date.now()+Math.random(),type,amount,status,time:new Date().toLocaleString()});save()}
function showSuccess(type,amount){const modal=$('#successModal');if(!modal)return;$('#successTitle').textContent=type==='deposit'?'Deposit Successful':'Withdrawal Request Submitted';$('#successText').textContent=type==='deposit'?'Your demo balance has been updated instantly.':'Your demo withdrawal has been recorded successfully.';$('#successAmount').textContent=(type==='deposit'?'+':'−')+money(amount);modal.classList.add('show')}
function deposit(){const input=$('#depositAmount'),amount=Number(input.value);if(!amount||amount<=0)return toast('Enter a valid demo deposit amount');state.balance+=amount;addTransaction('DEMO DEPOSIT',amount);renderBalance();input.value='';showSuccess('deposit',amount)}
function withdraw(){const input=$('#withdrawAmount'),amount=Number(input.value);if(!amount||amount<=0)return toast('Enter a valid demo withdrawal amount');if(amount>state.balance)return toast('Demo balance is too low');state.balance-=amount;addTransaction('DEMO WITHDRAWAL',amount,'PROCESSING');renderBalance();input.value='';showSuccess('withdraw',amount)}
function renderBalance(){if($('#balance'))$('#balance').textContent=money(state.balance);if($('#newBalance'))$('#newBalance').textContent=money(state.balance);if($('#withdrawBalance'))$('#withdrawBalance').textContent=money(state.balance)}
function renderTransactions(){const el=$('#transactionList');if(!el)return;const arr=state.transactions.slice().reverse();el.innerHTML=arr.length?'<div class="history-head"><div>Type</div><div>Amount</div><div>Status</div><div>Date</div><div>Account</div><div>Mode</div></div>'+arr.map(t=>`<div class="row"><div>${t.type}</div><div class="${t.type.includes('WITHDRAW')?'danger':'success'}">${t.type.includes('WITHDRAW')?'−':'+'}${money(t.amount)}</div><div class="${t.status==='COMPLETED'?'success':'muted'}">${t.status}</div><div>${t.time}</div><div>${state.name}</div><div>DEMO</div></div>`).join(''):'<div class="empty">No deposits or withdrawals yet.</div>'}
function renderHistory(){const el=$('#historyList');if(!el)return;const arr=state.trades.slice().reverse();el.innerHTML=arr.length?'<div class="history-head"><div>Contract</div><div>Direction</div><div>Stake</div><div>Result</div><div>Profit</div><div>Time</div></div>'+arr.map(t=>`<div class="row"><div>${t.contract}</div><div>${t.direction}</div><div>${money(t.stake)}</div><div class="${t.result==='WIN'?'success':t.result==='LOSS'?'danger':'muted'}">${t.result||'OPEN'}</div><div class="${t.profit>=0?'success':'danger'}">${t.result?(t.profit>=0?'+':'')+money(t.profit):'—'}</div><div>${t.time}</div></div>`).join(''):'<div class="empty">No demo trades yet.</div>'}
function chatInit(){const body=$('#chatBody');if(!body)return;if(!state.chat.length){state.chat.push({from:'bot',text:`Welcome to NovaTrade, ${state.name}! 👋`},{from:'bot',text:'Hello! I’m the NovaTrade demo assistant. How can I help you today?'},{from:'bot',text:'You can ask about demo deposits, withdrawals, trades or your account.'});save()}body.innerHTML=state.chat.map(m=>`<div class="bubble ${m.from==='me'?'me':'bot'}">${escapeHtml(m.text)}</div>`).join('');body.scrollTop=body.scrollHeight}
function escapeHtml(x){return x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function sendChat(){const input=$('#chatInput'),text=input.value.trim();if(!text)return;state.chat.push({from:'me',text});save();chatInit();input.value='';setTimeout(()=>{state.chat.push({from:'bot',text:'Thanks for your message! This is an automated demo response. Your message has been received.'});save();chatInit()},650)}
function initDepositWithdraw(){renderBalance();$('#depositBtn')?.addEventListener('click',deposit);$('#withdrawBtn')?.addEventListener('click',withdraw);$('#successClose')?.addEventListener('click',()=>$('#successModal').classList.remove('show'));$('#successBack')?.addEventListener('click',()=>location.href='index.html')}
function initChat(){chatInit();$('#sendChat')?.addEventListener('click',sendChat);$('#chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()})}
function initAccount(){const input=$('#nameInput');if(!input)return;input.value=state.name;$('#saveName').onclick=()=>{state.name=input.value.trim()||'Demo Trader';save();shell(document.body.dataset.page);toast('Demo account updated')}}
common();initAccount();initDepositWithdraw();initChat();renderTransactions();renderHistory();
