const KEY='ntV5';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{balance:1000,name:'Demo Trader',trades:[],transactions:[],chat:[]};
const $=s=>document.querySelector(s); const money=n=>'$'+Number(n).toFixed(2); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function toast(msg){const e=$('#toast');if(!e)return;e.textContent=msg;e.style.display='block';clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.style.display='none',2600)}
function shell(page){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const name=$('#accountName');if(name)name.textContent=state.name;const bal=$('#balance');if(bal)bal.textContent=money(state.balance)}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>location.href=b.dataset.page==='trade'?'index.html':b.dataset.page+'.html')}
function common(){nav();shell(document.body.dataset.page||'trade');}
function addTransaction(type,amount,status='COMPLETED'){state.transactions.push({id:Date.now()+Math.random(),type,amount,status,time:new Date().toLocaleString()});save()}
function deposit(){const input=$('#depositAmount'),amount=Number(input.value);if(!amount||amount<=0)return toast('Enter a valid demo deposit amount');state.balance+=amount;addTransaction('DEMO DEPOSIT',amount);$('#newBalance').textContent=money(state.balance);input.value='';toast(`Demo deposit of ${money(amount)} added`);renderBalance()}
function withdraw(){const input=$('#withdrawAmount'),amount=Number(input.value);if(!amount||amount<=0)return toast('Enter a valid demo withdrawal amount');if(amount>state.balance)return toast('Demo balance is too low');state.balance-=amount;addTransaction('DEMO WITHDRAWAL',amount);$('#newBalance').textContent=money(state.balance);input.value='';toast(`Demo withdrawal of ${money(amount)} recorded`);renderBalance()}
function renderBalance(){if($('#balance'))$('#balance').textContent=money(state.balance);if($('#newBalance'))$('#newBalance').textContent=money(state.balance)}
function renderTransactions(){const el=$('#transactionList');if(!el)return;const arr=state.transactions.slice().reverse();el.innerHTML=arr.length?'<div class="history-head"><div>Type</div><div>Amount</div><div>Status</div><div>Date</div><div>Account</div><div>Mode</div></div>'+arr.map(t=>`<div class="row"><div>${t.type}</div><div class="${t.type.includes('WITHDRAW')?'danger':'success'}">${t.type.includes('WITHDRAW')?'-':'+'}${money(t.amount)}</div><div class="success">${t.status}</div><div>${t.time}</div><div>${state.name}</div><div>DEMO</div></div>`).join(''):'<div class="empty">No deposits or withdrawals yet.</div>'}
function renderHistory(){const el=$('#historyList');if(!el)return;const arr=state.trades.slice().reverse();el.innerHTML=arr.length?'<div class="history-head"><div>Contract</div><div>Direction</div><div>Stake</div><div>Result</div><div>Profit</div><div>Time</div></div>'+arr.map(t=>`<div class="row"><div>${t.contract}</div><div>${t.direction}</div><div>${money(t.stake)}</div><div class="${t.result==='WIN'?'success':t.result==='LOSS'?'danger':'muted'}">${t.result||'OPEN'}</div><div class="${t.profit>=0?'success':'danger'}">${t.result?(t.profit>=0?'+':'')+money(t.profit):'—'}</div><div>${t.time}</div></div>`).join(''):'<div class="empty">No demo trades yet.</div>'}
function chatInit(){const body=$('#chatBody'); if(!body)return; if(!state.chat.length){state.chat.push({from:'bot',text:`Welcome to NovaTrade, ${state.name}! 👋`},{from:'bot',text:'You are connected to our demo support chat. This chat is simulated and no real support agent is online.'});save()}body.innerHTML=state.chat.map(m=>`<div class="bubble ${m.from==='me'?'me':'bot'}">${m.text}</div>`).join('');body.scrollTop=body.scrollHeight}
function sendChat(){const input=$('#chatInput'),text=input.value.trim();if(!text)return;state.chat.push({from:'me',text});save();chatInit();input.value='';setTimeout(()=>{state.chat.push({from:'bot',text:'Thanks for your message. This is an automated demo response.'});save();chatInit()},700)}
function initDepositWithdraw(){renderBalance();$('#depositBtn')?.addEventListener('click',deposit);$('#withdrawBtn')?.addEventListener('click',withdraw);}
function initChat(){chatInit();$('#sendChat')?.addEventListener('click',sendChat);$('#chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()})}
function initAccount(){const input=$('#nameInput');if(!input)return;input.value=state.name;$('#saveName').onclick=()=>{state.name=input.value.trim()||'Demo Trader';save();shell(document.body.dataset.page);toast('Demo account updated')};}
common();initAccount();initDepositWithdraw();initChat();renderTransactions();renderHistory();
